package com.payflow.payment;
import org.springframework.web.bind.annotation.*; import org.springframework.web.client.RestTemplate; import org.springframework.web.client.HttpClientErrorException; import org.springframework.web.client.HttpServerErrorException; import org.springframework.web.server.ResponseStatusException; import org.springframework.http.HttpStatus; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.kafka.core.KafkaTemplate; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*; import java.util.concurrent.TimeUnit;
@RestController @RequestMapping("/payments") public class PaymentController { final PaymentRepo repo; final RestTemplate http=new RestTemplate(); final StringRedisTemplate redis; final KafkaTemplate<String,Object> kafka; final String accountUrl;
public PaymentController(PaymentRepo r,StringRedisTemplate rd,KafkaTemplate<String,Object> k,@org.springframework.beans.factory.annotation.Value("${account-service-url}")String au){repo=r;redis=rd;kafka=k;accountUrl=au;}
@PostMapping @Transactional public Payment pay(@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody Map<String,Object>b){if(key!=null){String old=redis.opsForValue().get("idem:"+key);if(old!=null)return repo.findByTransactionId(old).orElseThrow();}
if(b.get("senderAccountId")==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"senderAccountId is required");if(b.get("merchantId")==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"merchantId is required");if(b.get("amount")==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"amount is required");
Long account;BigDecimal amount;try{account=Long.valueOf(b.get("senderAccountId").toString());amount=new BigDecimal(b.get("amount").toString());}catch(NumberFormatException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"senderAccountId and amount must be valid numbers");}
if(amount.compareTo(BigDecimal.ZERO)<=0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"amount must be greater than zero");
try{http.postForObject(accountUrl+"/accounts/"+account+"/debit",Map.of("amount",amount.toPlainString()),Object.class);}catch(HttpClientErrorException.NotFound e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Sender account not found");}catch(HttpClientErrorException|HttpServerErrorException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Payment declined: insufficient balance or account error");}
Payment p=new Payment();p.transactionId="TXN-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();p.senderAccountId=account;p.merchantId=Long.valueOf(b.get("merchantId").toString());p.amount=amount;p.status="SUCCESS";p=repo.save(p);if(key!=null)redis.opsForValue().set("idem:"+key,p.transactionId,24,TimeUnit.HOURS);kafka.send("payment-events",p.transactionId,Map.of("transactionId",p.transactionId,"senderAccountId",account,"merchantId",p.merchantId,"amount",amount,"status",p.status,"createdAt",p.createdAt.toString()));return p;}
@GetMapping("/{id}") public Payment one(@PathVariable String id){return repo.findByTransactionId(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Payment not found"));}
@GetMapping("/user/{accountId}") public List<Payment> user(@PathVariable Long accountId){return repo.findAll().stream().filter(p->p.senderAccountId.equals(accountId)).sorted(Comparator.comparing(p->p.createdAt,Comparator.reverseOrder())).toList();}}
