package com.payflow.account;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import org.springframework.http.HttpStatus; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@RestController @RequestMapping("/accounts") public class AccountController { final AccountRepo repo; public AccountController(AccountRepo r){repo=r;}
private Account getOrCreate(Long userId, BigDecimal initialBalance){return repo.findByUserId(userId).orElseGet(()->{try{return repo.save(new Account(userId,initialBalance));}catch(DataIntegrityViolationException e){return repo.findByUserId(userId).orElseThrow(()->e);}});}
private BigDecimal parseAmount(String raw){BigDecimal amount;try{amount=new BigDecimal(raw);}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"amount must be a valid number");}if(amount.compareTo(BigDecimal.ZERO)<=0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"amount must be greater than zero");return amount;}
@PostMapping public Account create(@RequestBody Map<String,Object> b){if(b.get("userId")==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"userId is required");Long u=Long.valueOf(b.get("userId").toString());return getOrCreate(u,new BigDecimal(b.getOrDefault("initialBalance","25000").toString()));}
@GetMapping("/user/{userId}") public Account byUser(@PathVariable Long userId){return getOrCreate(userId,new BigDecimal("25000"));}
@PostMapping("/{id}/deposit") @Transactional public Account deposit(@PathVariable Long id,@RequestBody Map<String,String>b){Account a=repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Account not found"));BigDecimal amount=parseAmount(b.get("amount"));a.balance=a.balance.add(amount);return repo.save(a);}
@PostMapping("/{id}/debit") @Transactional public Account debit(@PathVariable Long id,@RequestBody Map<String,String>b){Account a=repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Account not found"));BigDecimal amount=parseAmount(b.get("amount"));if(a.balance.compareTo(amount)<0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Insufficient balance");a.balance=a.balance.subtract(amount);return repo.save(a);}}
